force-app/main/default/objects/FailedPayload__c/FailedPayload__c.object-meta.xml
<CustomObject>
    <label>FailedPayload</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FailedPayloads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FailedPayload__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>ErrorMessage</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FailedPayload__c/fields/IsResolved__c.field-meta.xml
<CustomField>
    <fullName>IsResolved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsResolved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FailedPayload__c/fields/statusCode__c.field-meta.xml
<CustomField>
    <fullName>statusCode__c</fullName>
    <label>statusCode</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PayloadLogger.cls
public class PayloadLogger {
    
    // Méthode pour enregistrer le payload échoué
    
    public static void saveFailedPayload(String serializedPayload, String httpBody, integer statusCode) {
        // Remplire avec les donnée correspondantes
        Integer randomNumber = Math.mod(Math.abs(Crypto.getRandomInteger()), 1000000);         
        FailedPayload__c failedPayload = new FailedPayload__c();
        failedPayload.Name = 'Payload_' + randomNumber;
        
        failedPayload.Payload__c = serializedPayload; // Stocker le payload en JSON
        failedPayload.ErrorMessage__c = httpBody;
        failedPayload.statusCode__c = statusCode;
        failedPayload.IsResolved__c = false;  // Indiquer que ce problème n'est pas encore résolu
        
        try {
            insert failedPayload;
            
            System.debug('failedPayload inseré');
        } catch (DmlException e) {
            // Gérer les erreurs de DML ici, si nécessaire
            System.debug('Une erreur DML lors de l\'insertion de payload est survenue : ' + e+ ' Voici le payload échoué : '+ serializedPayload);
        }
    }
}